version: "3"
services:
  webapp:
    container_name: webapp
    build:
      context: .
    network_mode: host
    depends_on:
      - db
  db:
    container_name: world-db
    image: ghusta/postgres-world-db:2.4
    network_mode: host